import type { IntroEmbedInfo } from "@/lib/intro-embed";

// Same parent-domain list as components/twitch-embed.tsx — Twitch
// requires every embedding domain listed explicitly.
const EMBED_PARENTS = ["localhost", "youtube-ranker.vercel.app"];

function buildSrc(info: IntroEmbedInfo): string {
  switch (info.type) {
    case "youtube":
      // mute=1 alongside autoplay=1 is also just what browsers
      // require for autoplay to work at all — this isn't only a
      // stylistic choice, unmuted autoplay is blocked outright.
      return `https://www.youtube.com/embed/${info.id}?autoplay=1&mute=1&playsinline=1`;
    case "twitch_clip": {
      const parentParams = EMBED_PARENTS.map((p) => `parent=${p}`).join("&");
      return `https://clips.twitch.tv/embed?clip=${info.slug}&autoplay=true&muted=true&${parentParams}`;
    }
    case "twitch_video": {
      const parentParams = EMBED_PARENTS.map((p) => `parent=${p}`).join("&");
      return `https://player.twitch.tv/?video=${info.videoId}&autoplay=true&muted=true&${parentParams}`;
    }
  }
}

// Requirement: autoplay, start muted, never fullscreen — allow
// FullScreen is left off entirely (not just false) so there's no
// expand control at all.
//
// Width and aspect ratio are set via inline style rather than the
// Tailwind aspect-video/w-* classes this used before: aspect-ratio is
// what actually gives this box a height at all, since nothing else
// here has an intrinsic height. If that one class failed to generate
// for any reason, the box would collapse to whatever minimal height
// an iframe naturally renders at — full width, almost no height — a
// wide short black bar with the video showing as a tiny rectangle
// inside it, which is exactly the bug this fixes. Inline style can't
// have that problem: it's not something that needs to be generated by
// a build step at all.
export function IntroEmbed({ info }: { info: IntroEmbedInfo }) {
  return (
    <div
      className="relative mx-auto overflow-hidden rounded-md bg-black"
      style={{ width: "100%", maxWidth: 720, minWidth: 0, aspectRatio: "16 / 9" }}
    >
      <iframe
        className="absolute inset-0 h-full w-full"
        src={buildSrc(info)}
        title="Intro"
        allow="autoplay"
      />
    </div>
  );
}
